<a href="https://colab.research.google.com/github/as9786/NLP/blob/main/TopicModeling/LSA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LSA Scratch

In [1]:
import numpy as np

In [2]:
A = np.array([[0,0,0,1,0,1,1,0,0],[0,0,0,1,1,0,1,0,0],[0,1,1,0,2,0,0,0,0],[1,0,0,0,0,0,0,1,1]])

In [3]:
print('Shape of DTM : ',np.shape(A))

Shape of DTM :  (4, 9)


4개의 문서와 9개의 단어

In [39]:
# 특이값 분해
U,s,VT = np.linalg.svd(A,full_matrices=True)

In [40]:
U

array([[-2.39751712e-01,  7.51083898e-01,  9.05932925e-17,
        -6.15135834e-01],
       [-5.06077194e-01,  4.44029376e-01, -1.35889939e-16,
         7.39407727e-01],
       [-8.28495619e-01, -4.88580485e-01, -3.00875605e-17,
        -2.73649629e-01],
       [-7.19783140e-17, -2.24042335e-17,  1.00000000e+00,
         1.47971801e-16]])

In [41]:
U.shape

(4, 4)

In [42]:
VT

array([[-9.05730252e-17, -3.08298331e-01, -3.08298331e-01,
        -2.77536539e-01, -8.04917216e-01, -8.92159849e-02,
        -2.77536539e-01, -4.41881458e-17, -4.41881458e-17],
       [ 3.38857308e-17, -2.38904821e-01, -2.38904821e-01,
         5.84383395e-01, -2.60689306e-01,  3.67263060e-01,
         5.84383395e-01, -3.42420311e-17, -3.42420311e-17],
       [ 5.77350269e-01, -5.50814942e-17,  5.81928632e-17,
         1.38606015e-16, -1.41746067e-16,  1.66877179e-16,
        -8.34385896e-17,  5.77350269e-01,  5.77350269e-01],
       [ 2.32493354e-16, -3.54477649e-01, -3.54477649e-01,
         1.60978141e-01,  2.48851639e-01, -7.96828796e-01,
         1.60978141e-01, -5.08069894e-17, -5.08069894e-17],
       [-9.71445147e-17, -7.79217669e-01, -1.33887309e-02,
        -1.98151600e-01,  3.96303200e-01,  3.96303200e-01,
        -1.98151600e-01,  4.26271409e-17,  4.26271409e-17],
       [-2.88675135e-01,  3.11555335e-01, -7.80527867e-01,
        -2.42243133e-01,  2.34486266e-01,  2.344862

In [43]:
VT.shape

(9, 9)

In [14]:
s

array([2.68731789, 2.04508425, 1.73205081, 0.77197992])

In [16]:
S = np.zeros([4,9]) 
S[:4,:4] = np.diag(s)
S

array([[2.68731789, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 2.04508425, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.73205081, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.77197992, 0.        ,
        0.        , 0.        , 0.        , 0.        ]])

In [17]:
S.shape

(4, 9)

## 절단된 SVD

In [18]:
S = S[:2,:2]

In [19]:
S

array([[2.68731789, 0.        ],
       [0.        , 2.04508425]])

In [20]:
U = U[:,:2]
U

array([[-2.39751712e-01,  7.51083898e-01],
       [-5.06077194e-01,  4.44029376e-01],
       [-8.28495619e-01, -4.88580485e-01],
       [-7.19783140e-17, -2.24042335e-17]])

In [21]:
U.shape

(4, 2)

In [61]:
VT = VT[:2,:]
VT

array([[-9.05730252e-17, -3.08298331e-01, -3.08298331e-01,
        -2.77536539e-01, -8.04917216e-01, -8.92159849e-02,
        -2.77536539e-01, -4.41881458e-17, -4.41881458e-17],
       [ 3.38857308e-17, -2.38904821e-01, -2.38904821e-01,
         5.84383395e-01, -2.60689306e-01,  3.67263060e-01,
         5.84383395e-01, -3.42420311e-17, -3.42420311e-17]])

In [24]:
VT.shape

(2, 9)

In [26]:
A_truncated = np.dot(np.dot(U,S),VT) 
A_truncated

array([[ 1.10404704e-16, -1.68331693e-01, -1.68331693e-01,
         1.07644409e+00,  1.18172804e-01,  6.21607906e-01,
         1.07644409e+00, -2.41268428e-17, -2.41268428e-17],
       [ 1.53949304e-16,  2.02338650e-01,  2.02338650e-01,
         9.08112402e-01,  8.57953513e-01,  4.54836189e-01,
         9.08112402e-01,  2.90010320e-17,  2.90010320e-17],
       [ 1.67796375e-16,  9.25115881e-01,  9.25115881e-01,
         3.40069574e-02,  2.05257041e+00, -1.68331693e-01,
         3.40069574e-02,  1.32596097e-16,  1.32596097e-16],
       [ 1.59668195e-32,  7.05799891e-17,  7.05799891e-17,
         2.69079104e-17,  1.67638423e-16,  4.29464993e-19,
         2.69079104e-17,  1.01161717e-32,  1.01161717e-32]])

In [27]:
A_truncated.shape

(4, 9)

U : 각 행은 잠재 의미를 표현학 위한 수치화된 각각의 문서 vector

VT : 각 열은 잠재 의미를 표현하기 위한 수치화된 각각의 단어 vector

In [29]:
print(A.round(2))
print(A_truncated.round(2))

[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]
[[ 0.   -0.17 -0.17  1.08  0.12  0.62  1.08 -0.   -0.  ]
 [ 0.    0.2   0.2   0.91  0.86  0.45  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.03  2.05 -0.17  0.03  0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.  ]]


In [49]:
np.dot(A[0],VT[0])

-0.6442890634895055

In [50]:
np.dot(A[0],VT[1])

1.536029849211312

# LSA by Scikit 

In [51]:
from sklearn.decomposition import TruncatedSVD

In [57]:
svd_model = TruncatedSVD(n_components=2,n_iter=100)
svd_model.fit(A)
len(svd_model.components_)

2

In [62]:
svd_model.components_.round(2)

array([[-0.  ,  0.31,  0.31,  0.28,  0.8 ,  0.09,  0.28, -0.  , -0.  ],
       [ 0.  , -0.24, -0.24,  0.58, -0.26,  0.37,  0.58,  0.  ,  0.  ]])

In [63]:
VT.round(2)

array([[-0.  , -0.31, -0.31, -0.28, -0.8 , -0.09, -0.28, -0.  , -0.  ],
       [ 0.  , -0.24, -0.24,  0.58, -0.26,  0.37,  0.58, -0.  , -0.  ]])

# 실제 data

## Data loading

In [64]:
import pandas as pd
from sklearn.datasets import fetch_20newsgroups
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

In [65]:
dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=('headers', 'footers', 'quotes'))
documents = dataset.data
print('샘플의 수 :',len(documents))

샘플의 수 : 11314


In [66]:
print(dataset.target_names)

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


## 전처리

In [67]:
news_df = pd.DataFrame({'document':documents})
# 특수 문자 제거
news_df['clean_doc'] = news_df['document'].str.replace("[^a-zA-Z]", " ")
# 길이가 3이하인 단어는 제거 (길이가 짧은 단어 제거)
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))
# 전체 단어에 대한 소문자 변환
news_df['clean_doc'] = news_df['clean_doc'].apply(lambda x: x.lower())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  This is separate from the ipykernel package so we can avoid doing imports until


In [69]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [70]:
# NLTK로부터 불용어를 받아온다.
stop_words = stopwords.words('english')
tokenized_doc = news_df['clean_doc'].apply(lambda x: x.split()) # 토큰화
tokenized_doc = tokenized_doc.apply(lambda x: [item for item in x if item not in stop_words])

## TF-IDF

In [71]:
# 역토큰화 (토큰화 작업을 역으로 되돌림)
detokenized_doc = []
for i in range(len(news_df)):
    t = ' '.join(tokenized_doc[i])
    detokenized_doc.append(t)

news_df['clean_doc'] = detokenized_doc

In [72]:
vectorizer = TfidfVectorizer(stop_words='english', max_features= 1000, # 상위 1,000개의 단어를 보존 
max_df = 0.5, smooth_idf=True)

X = vectorizer.fit_transform(news_df['clean_doc'])

# TF-IDF 행렬의 크기 확인
print('TF-IDF 행렬의 크기 :',X.shape)

TF-IDF 행렬의 크기 : (11314, 1000)


## Topic Modeling

In [73]:
svd_model = TruncatedSVD(n_components=20, algorithm='randomized', n_iter=100, random_state=122)
svd_model.fit(X)
len(svd_model.components_)

20

In [74]:
terms = vectorizer.get_feature_names() # 단어 집합. 1,000개의 단어가 저장됨.

def get_topics(components, feature_names, n=5):
    for idx, topic in enumerate(components):
        print("Topic %d:" % (idx+1), [(feature_names[i], topic[i].round(5)) for i in topic.argsort()[:-n - 1:-1]])
get_topics(svd_model.components_,terms)

Topic 1: [('like', 0.21386), ('know', 0.20046), ('people', 0.19293), ('think', 0.17805), ('good', 0.15128)]
Topic 2: [('thanks', 0.32888), ('windows', 0.29088), ('card', 0.18069), ('drive', 0.17455), ('mail', 0.15111)]
Topic 3: [('game', 0.37064), ('team', 0.32443), ('year', 0.28154), ('games', 0.2537), ('season', 0.18419)]
Topic 4: [('drive', 0.53324), ('scsi', 0.20165), ('hard', 0.15628), ('disk', 0.15578), ('card', 0.13994)]
Topic 5: [('windows', 0.40399), ('file', 0.25436), ('window', 0.18044), ('files', 0.16078), ('program', 0.13894)]
Topic 6: [('chip', 0.16114), ('government', 0.16009), ('mail', 0.15625), ('space', 0.1507), ('information', 0.13562)]
Topic 7: [('like', 0.67086), ('bike', 0.14236), ('chip', 0.11169), ('know', 0.11139), ('sounds', 0.10371)]
Topic 8: [('card', 0.46633), ('video', 0.22137), ('sale', 0.21266), ('monitor', 0.15463), ('offer', 0.14643)]
Topic 9: [('know', 0.46047), ('card', 0.33605), ('chip', 0.17558), ('government', 0.1522), ('video', 0.14356)]
Topic 10

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
